### ISSUE TITLE
Setup Staging according to organisation prerequisites

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold#1]
- [x] has to be hosted on: 195.134.212.13
- [ ] uses staging naming convention: www2.
- [x] pulls content from this repository

**Comment by VonSub** [comment]
now running on www2.threefoldtoken.com should become www2.threefold.me

**Comment by kpobococ** [comment]
This was Wordpress redirection issue. I fixed it. Please verify

**Comment by VonSub** [comment]
verified
