### ISSUE TITLE
All links in second section are off.

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold#10]
Makes no sense, should link to grid.

**Comment by VonSub** [comment]
<img width="1202" alt="screen shot 2018-06-20 at 16 42 42" src="https://user-images.githubusercontent.com/29431263/41665773-175fea5a-74a9-11e8-91a9-cf28244535e9.png">

**Comment by VonSub** [comment]
Same Goes for the footer.

**Comment by despiegk** [comment]
we need to redo this one anyhow, see elena

**Comment by VonSub** [comment]
Links done for now. 
@despiegk Elena did not know what needed to be changed.

**Comment by VonSub** [comment]
verified
