### ISSUE TITLE
ROADMAP needs changes

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold#13]
![image](https://user-images.githubusercontent.com/6021844/41713062-6bd6d0fa-754c-11e8-8592-2abd4d3263b4.png)

- Tech Active: Q1 2017
- add Q2: Blockchain Launch (another bar next to grow grid)
- add: Tokens On Exchange: Q2 
- Tokens Promotion & Liquidity: Q3+
- Technology Exposure needs to be changed to: "Grid Developers Promotion"
- ThreeFold Fund -> ThreeFold Impact Fund to Q4 & Q1
- ThreeFold Incubator -> Q3 2018

the info below has priority on above:
see also https://threefoldfoundation.github.io/info_foundation/#/strategy/roadmap

**Comment by kpobococ** [comment]
Updated, please verify

**Comment by VonSub** [comment]
verified
