### ISSUE TITLE
team page has mistakes

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold#17]
# Questions

- where is the data where this is generated from
- where are the scripts doing this?

# to change

- ThreeFold Foundation -> ThreeFold Organization
- We are a nonprofit and international collaboration of individuals -> We are a team of people who are passionate ...
- remove links to GIG e.g. in text kristof
- mistakes in owen's profile (wrong chars)
- some people should not be there: Baker, Willem, Frank, 
- rename Developers community to Developers
- Ragheb should be moved to Ambassadors
- move following people from developers to ThreeFold
- move stela, Sophie, Pierre, Lucien from developers to threefold org
- remove following people from developers 
    - willem
    - nikolas krassas
    - geert
    - alexander
    - Iwan
    - Ekaterina
    - Chris, Pieter
    - Baker, Willem, Sacha
- people missing: chris Hutton

**Comment by VonSub** [comment]
@kpobococ @samaradel  can you answer the 2 questions.

**Comment by ehab-hassan** [comment]
M.conflict still working at the script to make it dynamic,  we updated it is static for now while he finishes

**Comment by ehab-hassan** [comment]
https://github.com/threefoldfoundation/www_foundation/issues/12
while we didn't use WordPress it fixed now at the online site
