### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold#3]
Add google analytics script to track web usage & where we need to improve for 1.1.0

- [x] Setup Script 
- [x] Add Script to website
- [x] Test Traffic

**Comment by VonSub** [comment]
Can only be used on WWW not the WWW2 (corrupts data)


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-100065546-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-100065546-1');
</script>

**Comment by VonSub** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-100065546-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-100065546-1');
</script>

**Comment by kpobococ** [comment]
This should be done tomorrow, when we replace current prod with WP version clone
