### ISSUE TITLE
team pics are not nice

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold#8]
![image](https://user-images.githubusercontent.com/6021844/41664098-3ae2b682-74a5-11e8-88b4-5318865532a4.png)

is very classic

there is no need to change something  which is working well

![image](https://user-images.githubusercontent.com/6021844/41664159-592bda60-74a5-11e8-8a49-724e6c0252be.png)

was dynamic (data comes from data file) and more modern.

the original one is also responsive.

the goal was to get data from centralized system so we can re-use everywhere.

**Comment by kpobococ** [comment]
There should be photos of each team member there, not just blank squares. I'm guessing, no photo has been uploaded for these members. This is how it should look when the photos are uploaded:
![image](https://user-images.githubusercontent.com/144050/41664923-72706e8c-74af-11e8-981a-3fb2648c1675.png)

**Comment by despiegk** [comment]
- I know but that not the point, point is people like the way how it was on the original site.
- We don't see a reason to change that, it was nice, people like it and the data gets from dynamic repo.

**Comment by despiegk** [comment]
please,using the data and the code we already have, nothing we need to do different, copy paste (colors or some style elements we can change but inside the existing implementation), please use the people who alread did it, nothing static, please

**Comment by ehab-hassan** [comment]
Samar updates Anton with (static) team page and waiting for mr.conflict to make it dynamic tomorrow. As he will setup Jumpscale on the VM and configure the python pull script

**Comment by VonSub** [comment]
verified
